### PR TITLE
swap exists

### PR DESCRIPTION
**Pull request by ghost**
i edited this in a web browser in debian noroot so be proud

### CODE REVIEW

**Comment by ghost** [comment]
Wait no i made a typo on line 70 dont accept yet

**Comment by ghost** [comment]
ok i fixed the typo no you can accept

**Comment by PowerMan2206** [comment]
Nah, I just added Swapfile support which is at least like 5% better than a partition. Also there's another typo on line 66.

**Comment by ghost** [comment]
_*curses*_

**Pull request closed without merging**
